If httpd is not found, look for other common variants
Different *nix distributions will use different names for the Apache binary: httpd, apachectl, and apache2ctl.

This commit ensures the script tries the known alternatives and finds one that'll work before spitting out an error.

diff --git a/bin/validate-htaccess b/bin/validate-htaccess
--- a/bin/validate-htaccess
+++ b/bin/validate-htaccess
@@ -16,7 +16,7 @@
 #
 # 0 - The syntax is valid.
 # 1 - The syntax is invalid, see STDERR for details.
-# 2 - The httpd binary could not be found.
+# 2 - The Apache binary could not be found.
 # 3 - The given file does not exist.
 # 4 - The current Apache configuration (without including the file being tested)
 #     appears to be invalid, so we cannot safely proceed.
@@ -24,11 +24,23 @@
 # Author: Liquid Web
 # License: MIT
 
+declare -a variants
+
 file=${1:?No configuration file specified.}
 
-# Ensure that httpd is available.
-if ! command -v httpd &> /dev/null; then
-    echo 'Unable to find the httpd binary, is Apache2 installed?' 1>&2
+# First, figure out which Apache variant we're working with.
+variants=( httpd apachectl apache2ctl )
+
+for variant in "${variants[@]}"; do
+    if command -v "$variant" &> /dev/null; then
+        apache_binary="$variant"
+        break
+    fi
+done
+
+# Ensure that Apache is available.
+if [ -z "$apache_binary" ]; then
+    echo 'Unable to find the Apache binary, is Apache2 installed?' 1>&2
     exit 2
 fi
 
@@ -40,14 +52,14 @@ fi
 
 # Verify that the current configuration passes; if it doesn't, it won't
 # magically be fixed by throwing more on top of it.
-if ! httpd -t -C "ServerName example.com" 2> /dev/null; then
+if ! "$apache_binary" -t -C "ServerName example.com" 2> /dev/null; then
     echo "The current Apache environment is misconfigured.
 Please resolve these issues before attempting to validate ${file}." 1>&2
     exit 4
 fi
 
 # Get the name of the current configuration file.
-current_config=$(httpd -V \
+current_config=$("$apache_binary" -V \
     | grep -E -o -e 'SERVER_CONFIG_FILE="(.+)"' \
     | sed 's/SERVER_CONFIG_FILE=//; s/"//g')
 
@@ -55,9 +67,9 @@ current_config=$(httpd -V \
 tmpfile=$(mktemp)
 cat "$file" > "$tmpfile"
 
-# Now, use Apache to validate itself, injecting $FILE into the current
+# Now, use Apache to validate itself, injecting $file into the current
 # server environment.
-results=$(httpd -t -C "Include ${current_config}" -f "$tmpfile" -C "ServerName example.com" 2>&1)
+results=$("$apache_binary" -t -C "Include ${current_config}" -f "$tmpfile" -C "ServerName example.com" 2>&1)
 exit_code=$?
 
 # Remove the temp file.
